# Generated by Django 3.2.5 on 2022-03-06 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_availability_booked',
            fields=[
                ('booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('patied_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('appointment_date', models.DateField()),
                ('appointment_start_time', models.TimeField()),
                ('appointment_end_time', models.TimeField()),
                ('booking_request_timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('user_id_approver', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
