# Generated by Django 3.2.5 on 2022-04-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_hospital_system', '0003_auto_20220403_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
